feat: adding validation of task defination

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -36,6 +36,13 @@ jobs:
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2
 
+    - name: Validate Task Definition
+      run: |
+        if [ ! -f ${{ env.ECS_TASK_DEFINITION }} ]; then
+          echo "Task definition file not found"
+          exit 1
+        fi
+
     - name: Build, tag, and push image to Amazon ECR
       id: build-image
       env:
